### ISSUE TITLE
Incomplete domain setting

### ISSUE THREAD

**Issue by shenwei356** [erikvdbergh/erikvdbergh.github.io#2]
Hi Erik,

Your domain setting seems incomplete. The http://oceanbioinformatics.com/ works.

But the http://www.oceanbioinformatics.com/ unreachable,  "A" record "www" needed since you set this URL as the default page at this repo page and github user profile page.

**Comment by erikvdbergh** [comment]
Thanks for reporting. I've made a CNAME redirect to oceanbioinformatics.com. It might be a while for all DNS records to update so I'll test again in a few hours.

**Comment by erikvdbergh** [comment]
www.oceanbioinformatics.com is now working
